package org.javalens.core.buildsystem;

import org.eclipse.jdt.core.IJavaProject;
import org.eclipse.jdt.core.IType;
import org.javalens.core.JdtServiceImpl;
import org.javalens.core.fixtures.TestEnvironment;
import org.javalens.core.fixtures.TestProjectHelper;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * Bug H — annotation processing was never enabled, so symbols generated by processors like
 * Lombok / MapStruct / Dagger / JPA Metamodel were invisible to JDT analysis.
 *
 * <p>The fix wires APT on the {@code IJavaProject}: enables the {@code COMPILER_PROCESS_ANNOTATIONS}
 * compiler option, calls {@link org.eclipse.jdt.apt.core.util.AptConfig#setEnabled} and registers
 * the processor jars declared in pom {@code <annotationProcessorPaths>}.
 *
 * <p>This test stages a real Lombok build: it copies the {@code lombok-maven} fixture, runs
 * {@code mvn dependency:resolve} to download lombok into {@code ~/.m2}, and asserts that
 * {@code AptConfig.isEnabled} is {@code true} on the configured project and that the
 * {@code COMPILER_PROCESS_ANNOTATIONS} compiler option was set to {@code enabled}. The actual
 * generation of Lombok methods inside JDT additionally requires Lombok's Eclipse agent (which
 * we can't ship as part of a unit test); the assertions here cover the wiring this code is
 * responsible for.
 */
class AnnotationProcessingTest {

    @RegisterExtension
    TestProjectHelper helper = new TestProjectHelper();

    @Test
    @DisplayName("Lombok project: APT is enabled and processor jar is on the factory path")
    void aptIsEnabledForLombokProject() throws Exception {
        String mvn = resolveMavenBinary();
        TestEnvironment.requireOrSkip(mvn,
            "Maven binary (APT wiring needs mvn to seed lombok in ~/.m2)");

        String previousOverride = System.getProperty("javalens.maven.binary");
        System.setProperty("javalens.maven.binary", mvn);
        try {
            Path projectRoot = helper.copyFixture("lombok-maven");
            // Seed ~/.m2 with the lombok jar so detectMavenAnnotationProcessors can find it.
            runMaven(mvn, projectRoot, "dependency:resolve", "-B", "-q");

            JdtServiceImpl service = new JdtServiceImpl();
            service.loadProject(projectRoot);

            IJavaProject javaProject = service.getJavaProject();
            assertEquals(true,
                org.eclipse.jdt.apt.core.util.AptConfig.isEnabled(javaProject),
                "Expected AptConfig.isEnabled to return true for a project with declared processors");

            // The fixture itself loads — LombokBean type is resolvable as a regular source
            // class regardless of generation. (Whether @Data getters appear in IType.getMethods
            // depends on Lombok's Eclipse agent which is not a part of this test.)
            IType bean = service.findType("com.example.LombokBean");
            assertNotNull(bean, "LombokBean source type should resolve");
        } finally {
            if (previousOverride == null) System.clearProperty("javalens.maven.binary");
            else System.setProperty("javalens.maven.binary", previousOverride);
        }
    }

    private static void runMaven(String mvnBinary, Path projectRoot, String... goals)
            throws IOException, InterruptedException {
        java.util.List<String> command = new java.util.ArrayList<>();
        command.add(mvnBinary);
        for (String g : goals) command.add(g);
        Process p = new ProcessBuilder(command)
            .directory(projectRoot.toFile())
            .redirectErrorStream(true)
            .start();
        StringBuilder captured = new StringBuilder();
        try (var reader = new java.io.BufferedReader(new java.io.InputStreamReader(p.getInputStream()))) {
            String line;
            while ((line = reader.readLine()) != null) {
                if (captured.length() < 8192) captured.append(line).append('\n');
            }
        }
        boolean done = p.waitFor(5, TimeUnit.MINUTES);
        if (!done) {
            p.destroyForcibly();
            throw new RuntimeException("mvn " + String.join(" ", goals) + " timed out\n" + captured);
        }
        if (p.exitValue() != 0) {
            throw new RuntimeException("mvn " + String.join(" ", goals)
                + " failed with exit code " + p.exitValue() + "\n" + captured);
        }
    }

    private static String resolveMavenBinary() {
        boolean isWindows = System.getProperty("os.name").toLowerCase().contains("win");
        String binaryName = isWindows ? "mvn.cmd" : "mvn";

        try {
            Process p = new ProcessBuilder(binaryName, "-v").redirectErrorStream(true).start();
            try (var r = new java.io.BufferedReader(new java.io.InputStreamReader(p.getInputStream()))) {
                while (r.readLine() != null) { /* drain */ }
            }
            p.waitFor();
            if (p.exitValue() == 0) return binaryName;
        } catch (IOException | InterruptedException ignored) {
            if (Thread.interrupted()) Thread.currentThread().interrupt();
        }

        Path wrapperDists = Path.of(System.getProperty("user.home"), ".m2", "wrapper", "dists");
        if (!Files.isDirectory(wrapperDists)) return null;
        try (Stream<Path> distros = Files.list(wrapperDists)) {
            for (Path distro : distros.toList()) {
                try (Stream<Path> hashes = Files.list(distro)) {
                    for (Path hashDir : hashes.toList()) {
                        Path bin = hashDir.resolve("bin").resolve(binaryName);
                        if (Files.isRegularFile(bin)) return bin.toString();
                    }
                }
            }
        } catch (IOException ignored) {}
        return null;
    }
}
